app_name: bisakerja-api
environment: development
http_port: "8080"
shutdown_timeout: 10s
worker_tick_interval: 15s
scraper_page_size: 30
scraper_max_pages: 1
scraper_keywords:
  - backend
  - frontend
  - intern
auth_jwt_secret: change-this-jwt-secret
auth_access_token_ttl: 15m
auth_refresh_token_ttl: 168h
